//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="operators", Namespace="http://tempuri.org/")]
    public enum operators : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subtract = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiply = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Divide = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.SimpleCalculatorSoap")]
    public interface SimpleCalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doTheMath", ReplyAction="*")]
        double doTheMath(double fn, double sn, Calculator.CalculatorService.operators operat);
        
        // CODEGEN: Generating message contract since element name getCalculationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCalculations", ReplyAction="*")]
        Calculator.CalculatorService.getCalculationsResponse getCalculations(Calculator.CalculatorService.getCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalculations", Namespace="http://tempuri.org/", Order=0)]
        public Calculator.CalculatorService.getCalculationsRequestBody Body;
        
        public getCalculationsRequest() {
        }
        
        public getCalculationsRequest(Calculator.CalculatorService.getCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCalculationsRequestBody {
        
        public getCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator.CalculatorService.getCalculationsResponseBody Body;
        
        public getCalculationsResponse() {
        }
        
        public getCalculationsResponse(Calculator.CalculatorService.getCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Calculator.CalculatorService.ArrayOfString getCalculationsResult;
        
        public getCalculationsResponseBody() {
        }
        
        public getCalculationsResponseBody(Calculator.CalculatorService.ArrayOfString getCalculationsResult) {
            this.getCalculationsResult = getCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleCalculatorSoapChannel : Calculator.CalculatorService.SimpleCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleCalculatorSoapClient : System.ServiceModel.ClientBase<Calculator.CalculatorService.SimpleCalculatorSoap>, Calculator.CalculatorService.SimpleCalculatorSoap {
        
        public SimpleCalculatorSoapClient() {
        }
        
        public SimpleCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double doTheMath(double fn, double sn, Calculator.CalculatorService.operators operat) {
            return base.Channel.doTheMath(fn, sn, operat);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalculatorService.getCalculationsResponse Calculator.CalculatorService.SimpleCalculatorSoap.getCalculations(Calculator.CalculatorService.getCalculationsRequest request) {
            return base.Channel.getCalculations(request);
        }
        
        public Calculator.CalculatorService.ArrayOfString getCalculations() {
            Calculator.CalculatorService.getCalculationsRequest inValue = new Calculator.CalculatorService.getCalculationsRequest();
            inValue.Body = new Calculator.CalculatorService.getCalculationsRequestBody();
            Calculator.CalculatorService.getCalculationsResponse retVal = ((Calculator.CalculatorService.SimpleCalculatorSoap)(this)).getCalculations(inValue);
            return retVal.Body.getCalculationsResult;
        }
    }
}
